steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/tomaskracka/flask', '.']
  id: 'docker-image-build-for-gcr'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/tomaskracka/flask']
  id: 'docker-image-push-gcr'
  waitFor: ['docker-image-build-for-gcr']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'tomaskracka/flask', '.']
  id: 'docker-image-build-for-dockerhub'

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - app
  - deploy
  - --quiet
  - app.yaml
  - --image-url=gcr.io/$PROJECT_ID/tomaskracka/flask
  id: 'flask'

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login -u username -p $$PASSWORD']
  id: 'docker-login'
  secretEnv: ['PASSWORD']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'tomaskracka/flask']
  id: 'docker-image-push-docker-hub'
  waitFor: ['docker-login', 'docker-image-build-for-dockerhub']

secrets:
- kmsKeyName: projects/kracka-216804/locations/global/keyRings/dockerhub/cryptoKeys/hub
  secretEnv:
    PASSWORD: CiQAjxv7u7VND5v8RCJk7qw5r57jxa/GB2RD+VpWhHaouYXpOnESNgC0Rr7ywXvNQYPp6H3H+jlCiFILfBgDLVh2c+hsojMnmVAvXzh1rfONlXn1hKLKG0AbEu97ew==
